
default: &default
  adapter: postgresql
  encoding: unicode
  database: ruby_battle_organizer
  pool: 5
  host: localhost
  timeout: 5000
  username: <%= '' %>
  password: <%= '' %>
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
